module.exports = {
    handleRegisterUser: require('./handle-register-user'),
    handleAuthenticateUser: require('./handle-authenticate-user'),
    handleRetrieveUser: require('./handle-retrieve-user'),
    handleAddFood: require('./handle-add-food'),
    handleFindFood: require('./handle-find-food'),
    handleToggleFoodUserDiet: require('./handle-toggle-food-user-diet'),
    handleRetrieveSavedFood: require('./handle-retrieve-saved-food'),
    handleAddFoodUserDiet: require('./handle-add-food-user-diet'),
    handleRetrieveDiet: require('./handle-retrieve-diet'),
    handleRetrieveArticles: require('./handle-retrieve-articles'),
    handleAddUserArticles: require('./handle-add-user-articles'),
    handleAddUserRecipes: require('./handle-add-user-recipes'),
    handleRetrieveSavedArticles: require('./handle-retrieve-saved-articles'),
    handleRetrieveChosenArticle: require('./handle-retrieve-chosen-article'),
    handleRetrieveRecipe: require('./handle-retrieve-recipe'),
    handleRetrieveRecipes: require('./handle-retrieve-recipes'),
    handleRetrieveSavedRecipes: require('./handle-retrieve-saved-recipes'),
    handleRetrieveChosenDiet: require('./handle-retrieve-chosen-diet'),
    handleRetrieveWorkout: require('./handle-retrieve-workout'),
    handleRetrieveMuscularGroup: require('./handle-retrieve-muscular-group'),
    handleToggleWorkoutsUser: require('./handle-toggle-workouts-user'),
    handleRetrieveSavedWorkouts: require('./handle-retrieve-saved-workouts'),
    handleSavePictureUser: require('./handle-save-picture-user'),
    handleRetrievePictureUser: require('./handle-retrieve-picture-user'),
    handleSaveWeightUser: require('./handle-save-weight-user'),
    handleDeleteUser: require('./handle-delete-user')
}